### ISSUE TITLE
Does bob.sp link against boost?

### ISSUE THREAD

**Issue by 183amir** [conda-forge/bob.sp-feedstock#4]
Hi @anjos, I was wondering if `bob.sp` links against `boost`? According to the logs I could not find any proof. For example: https://travis-ci.org/conda-forge/bob.sp-feedstock/jobs/130457503

**Comment by anjos** [comment]
Normally, yes.

You can manually check what is the precise set by 'ldd'ing the generated '.so' file.

**Comment by 183amir** [comment]
As far as I can see it doesn't:

```
ldd ~/miniconda/envs/bob-2.2.0-py27_0/lib/python2.7/site-packages/bob/sp/libbob_sp.so 
    linux-vdso.so.1 (0x00007ffca39f2000)
    libbob_core.so => not found
    libblitz.so.0 => /home/amir/miniconda/envs/bob-2.2.0-py27_0/lib/python2.7/site-packages/bob/sp/../../../../libblitz.so.0 (0x00007f33ffa73000)
    libstdc++.so.6 => /home/amir/miniconda/envs/bob-2.2.0-py27_0/lib/python2.7/site-packages/bob/sp/../../../../libstdc++.so.6 (0x00007f33ff6b6000)
    libm.so.6 => /usr/lib/libm.so.6 (0x00007f33ff3b2000)
    libgcc_s.so.1 => /home/amir/miniconda/envs/bob-2.2.0-py27_0/lib/python2.7/site-packages/bob/sp/../../../../libgcc_s.so.1 (0x00007f33ff19b000)
    libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f33fef7d000)
    libc.so.6 => /usr/lib/libc.so.6 (0x00007f33febdc000)
    /usr/lib64/ld-linux-x86-64.so.2 (0x0000557569312000)
```

Is this normal?

**Comment by anjos** [comment]
If you mean "directly", then as you can see, it does not. That is backed-up by its setup.py file, which also does not require boost.

Nevertheless, if you inspect `libbob_core.so`, you'll find it links against boost system. So, _indirectly_, `libob_sp.so` links against boost system.

**Comment by 183amir** [comment]
If bob.core is compiled with boost and you compile bob.sp with it, will this bob.sp work with another bob.core that is compiled with a newer boost?

**Comment by anjos** [comment]
Yes, for as long as the ABI is not changed.
